In [18]:
import os
import pandas as pd
print(os.getcwd())

C:\Users\Jose Alvarez\Documents\Projects\weighted-pdp\src


In [22]:
from folktables import ACSDataSource, ACSEmployment

# all US states
states = sorted(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 
                 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 
                 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 
                 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 
                 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'])
# state codes
state_codes = pd.read_csv(os.path.join('..', 'data', 'state_codes.csv'), )

# data folder
data_source = ACSDataSource(survey_year='2017', horizon='1-Year', survey='person', root_dir=os.path.join('..', 'data'))

In [23]:
state_codes.head(5)

Name  numeric USPS
0     Alabama         1   AL
1      Alaska         2   AK
2     Arizona         4   AZ
3    Arkansas         5   AR
4  California         6   CA

In [4]:
# e.g., run for Florida
state_data = data_source.get_data(states=['FL'], download=True)

In [7]:
features, label, group = ACSEmployment.df_to_numpy(state_data)

In [8]:
features

array([[30., 17.,  5., ...,  2.,  2.,  8.],
       [ 9.,  6.,  5., ...,  2.,  1.,  8.],
       [ 6.,  3.,  5., ...,  2.,  1.,  8.],
       ...,
       [30., 21.,  5., ...,  2.,  1.,  2.],
       [87., 22.,  1., ...,  2.,  2.,  1.],
       [69., 16.,  5., ...,  1.,  1.,  2.]])

In [9]:
label

array([ True, False, False, ..., False, False, False])

In [10]:
group

array([8, 8, 8, ..., 2, 1, 2], dtype=int64)

In [11]:
features, label, group = ACSEmployment.df_to_pandas(state_data)

In [13]:
features.head(5)

AGEP  SCHL  MAR  RELP  DIS  ESP  CIT  MIG  MIL  ANC  NATIVITY  DEAR  DEYE  \
0  30.0  17.0  5.0   0.0  2.0  0.0  4.0  1.0  4.0  1.0       2.0   2.0   2.0   
1   9.0   6.0  5.0   2.0  2.0  7.0  1.0  1.0  0.0  2.0       1.0   2.0   2.0   
2   6.0   3.0  5.0   2.0  2.0  7.0  1.0  1.0  0.0  2.0       1.0   2.0   2.0   
3   1.0   0.0  5.0   2.0  2.0  7.0  1.0  1.0  0.0  2.0       1.0   2.0   2.0   
4  41.0  17.0  4.0  13.0  2.0  0.0  1.0  1.0  4.0  1.0       1.0   2.0   2.0   

   DREM  SEX  RAC1P  
0   2.0  2.0    8.0  
1   2.0  1.0    8.0  
2   2.0  1.0    8.0  
3   0.0  1.0    8.0  
4   2.0  1.0    8.0

In [15]:
label.head(5)

ESR
0   True
1  False
2  False
3  False
4  False

In [16]:
group.head(5)

RAC1P
0      8
1      8
2      8
3      8
4      8

In [17]:
# TODO:
# avoid re-loading the data
# what is the group object? 
# what are the labels here?